DROP TABLE IF EXISTS product_subcategory;
DROP TABLE IF EXISTS product_category;

CREATE TABLE IF NOT EXISTS product_category
(
    product_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category_name VARCHAR NOT NULL UNIQUE,
    image_path VARCHAR
);

CREATE TABLE IF NOT EXISTS product_subcategory
(
    product_subcategory_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_category_id INT REFERENCES product_category(product_id),
    subcategory_name VARCHAR NOT NULL UNIQUE,
    image_path VARCHAR
);