-- PREPARED CODE FOR POSTGRESQL
DROP TABLE IF EXISTS image;
DROP TABLE IF EXISTS carts_products;
DROP TABLE IF EXISTS cart;
DROP TABLE IF EXISTS product;
DROP TABLE IF EXISTS product_type;
DROP TABLE IF EXISTS persons_roles;
DROP TABLE IF EXISTS roles;
DROP TABLE IF EXISTS person_credentials;
DROP TABLE IF EXISTS persons;
DROP TABLE IF EXISTS product_category;

CREATE TABLE IF NOT EXISTS persons
(
    person_id      INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    person_name    VARCHAR(50),
    person_surname VARCHAR(50)
);

CREATE TABLE IF NOT EXISTS product_category
(
    category_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category_name VARCHAR NOT NULL UNIQUE,
    image_path VARCHAR
);

CREATE TABLE IF NOT EXISTS product_type
(
    product_type_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_type    VARCHAR(50) UNIQUE,
    product_category_id INT REFERENCES product_category(category_id),
    image_path VARCHAR
);



CREATE TABLE IF NOT EXISTS product
(
    id              INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_type_id INT              NOT NULL REFERENCES product_type (product_type_id),
    product_name    VARCHAR(100)     NOT NULL,
    description     VARCHAR(100)     NOT NULL,
    price           DOUBLE PRECISION NOT NULL,
    amount          INTEGER          NOT NULL
);

CREATE TABLE IF NOT EXISTS cart
(
    cart_id   INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    person_id INT NOT NULL REFERENCES persons (person_id)
);

CREATE TABLE IF NOT EXISTS carts_products
(
    cart_id INT REFERENCES cart (cart_id),
    product_id INT REFERENCES product (id)
);

CREATE TABLE IF NOT EXISTS image
(
    id               INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    file_name        VARCHAR(100) NOT NULL,
    size             BIGINT       NOT NULL,
    content_type     VARCHAR(50)  NOT NULL,
    is_preview_image BOOLEAN      NOT NULL,
    bytes            BYTEA        NOT NULL,
    product_id       INT REFERENCES product (id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS person_credentials
(
    id              INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    person_id       INT                 NOT NULL REFERENCES persons (person_id) ON DELETE CASCADE,
    person_email    varchar(100) UNIQUE NOT NULL,
    person_password varchar(256)        NOT NULL
);

CREATE TABLE IF NOT EXISTS roles
(
    id        INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    role_name VARCHAR(30) NOT NULL
);

INSERT INTO roles (role_name)
VALUES ('ROLE_ADMIN'),
       ('ROLE_USER');

CREATE TABLE IF NOT EXISTS persons_roles
(
    person_id INT NOT NULL REFERENCES persons (person_id) ON DELETE CASCADE,
    roles_id  INT NOT NULL REFERENCES roles (id)
);


-- ////////////////////////
-- ////////////////////////
-- ////////////////////////


INSERT INTO persons (person_name, person_surname)
VALUES ('Bob', 'Smith'),
       ('John', 'Vincent');


INSERT INTO person_credentials (person_id, person_email, person_password)
VALUES (1, 'admin@admin.admin',
        '$2a$12$kEXJlUJz6mluBbSwCkBb9.CbSSQF5PkRyQPAxS75FRYSOKYx/zDI2'), --password:   Zz123456   (BCrypted)
       (2, 'user@user.user', '$2a$12$XIwBfESBnmlcNo7bOzp1fe.hRjQZMdz8Pk1SnwLsIOW1L80x9v4uO'); --password:   Aa123456

INSERT INTO persons_roles (person_id, roles_id)
VALUES (1, 1),
       (2, 2);



INSERT INTO product_category(category_name, image_path)
VALUES ('home_appliance', '/img/categories/homeapp_category.jpg'),
       ('smartphones_and_gadgets', '/img/categories/smartph_category.jpg'),
       ('tv_and_multimedia', '/img/tv_multi_category.jpg'),
       ('pc_and_parts', '/img/pc_category.jpg');

INSERT INTO product_type(product_type, product_category_id, image_path)
VALUES ('refrigerators', 1, '/img/subcategories/refrigerators_subcategory.jpg'),
       ('stoves', 1, '/img/subcategories/stoves_subcategory.jpg'),
       ('smartphones', 2, '/img/subcategories/smartphones_subcategory.jpg'),
       ('smartwatches', 2, '/img/subcategories/smartwatches_subcategory.jpg'),
       ('tvs', 3, '/img/subcategories/tvs_subcategory.jpg'),
       ('game_consoles', 3, '/img/subcategories/gameconsoles_subcategory.jpg'),
       ('laptops', 4, '/img/subcategories/laptops_subcategory.jpg'),
       ('pc_parts', 4 ,'/img/subcategories/pc_parts_subcategory.jpg');

INSERT INTO product (product_type_id, product_name, description, price, amount)
VALUES (1, 'REFRIGERATOR LG', 'DESCRIPTION', 345.23, 36),
       (1, 'REFRIGERATOR SAMSUNG', 'DESCRIPTION', 234, 64);