-- PREPARED CODE FOR POSTGRESQL
DROP TABLE IF EXISTS persons_roles;
DROP TABLE IF EXISTS roles;
DROP TABLE IF EXISTS person_credentials;
DROP TABLE IF EXISTS image;
DROP TABLE IF EXISTS product;

CREATE TABLE IF NOT EXISTS product
(
    id           INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_name VARCHAR(100)     NOT NULL,
    description  VARCHAR(100)     NOT NULL,
    price        DOUBLE PRECISION NOT NULL,
    amount       INTEGER          NOT NULL
);

CREATE TABLE IF NOT EXISTS image
(
    id               INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    file_name        VARCHAR(100) NOT NULL,
    size             BIGINT       NOT NULL,
    content_type     VARCHAR(50)  NOT NULL,
    is_preview_image BOOLEAN      NOT NULL,
    bytes            BYTEA        NOT NULL,
    product_id       INT REFERENCES product (id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS person_credentials
(
    id              INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    person_email    varchar(100) UNIQUE NOT NULL,
    person_password varchar(256)         NOT NULL
);

CREATE TABLE IF NOT EXISTS roles
(
    id        INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    role_name VARCHAR(30) NOT NULL
);

INSERT INTO roles (role_name)
VALUES ('ROLE_ADMIN'),
       ('ROLE_USER');

CREATE TABLE IF NOT EXISTS persons_roles
(
    person_credentials_id INT NOT NULL REFERENCES person_credentials (id),
    roles_id              INT NOT NULL REFERENCES roles (id)
);


-- ////////////////////////
-- ////////////////////////
-- ////////////////////////


INSERT INTO person_credentials (person_email, person_password)
VALUES ('admin@admin.admin', '$2a$12$kEXJlUJz6mluBbSwCkBb9.CbSSQF5PkRyQPAxS75FRYSOKYx/zDI2'),   --password:   Zz123456   (BCrypted)
       ('user@user.user', '$2a$12$XIwBfESBnmlcNo7bOzp1fe.hRjQZMdz8Pk1SnwLsIOW1L80x9v4uO');    --password:   Aa123456

INSERT INTO persons_roles (person_credentials_id, roles_id)
VALUES (1, 1),
       (2, 2);