DROP TABLE IF EXISTS person_credentials;

CREATE TABLE IF NOT EXISTS person_credentials
(
    id           INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    person_email varchar(100) NOT NULL,
    person_password     varchar(50)  NOT NULL
);

INSERT INTO person_credentials(person_email, person_password)
VALUES ('mail1@mail.ru', 'password1'),
       ('mail2@mail.ru', 'password2');