DROP TABLE IF EXISTS product_type;

CREATE TABLE IF NOT EXISTS product_type
(
    product_type_id INT GENERATED BY DEFAULT AS IDENTITY,
    product_id INT NOT NULL REFERENCES product(product_id),
    product_type VARCHAR(50) UNIQUE
)