DROP TABLE IF EXISTS product;

CREATE TABLE IF NOT EXISTS product
(
    product_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cart_id INT REFERENCES cart(cart_id),
    product_type INT NOT NULL REFERENCES product_type(product_type_id),
    product_name VARCHAR(100) NOT NULL,
    description VARCHAR(100) NOT NULL,
    price DOUBLE PRECISION NOT NULL,
    amount INTEGER NOT NULL
);